channels:
  - conda-forge
  - bioconda
dependencies:
  - python==3.6.6
# Bioinformatics tools
  - ete3==3.1.1
  - scikit-bio==0.5.4
  - biopython==1.72
  - mash==2.1
  - entrez-direct==10.2
# General
  - pathos==0.2.1
  - pandas==0.22.0
  - numpy==1.15.2
  - click==7.0
  - tenacity==5.0.2
  - logbook==1.4.1
  - attrs==18.2.0
